#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "psteinroe"
email = "philipp@steinroetter.com"

[remotes.origin]
auto-track-bookmarks = '*'

[ui]
default-command = "log"

[aliases]
s = ["status"]
d = ["diff"]
l = ["log", "-r", "trunk()..@"]
